[repository]
name = "hyprRiver"
authors = ["Zakk"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "2cf61ecab432bea378c1525a0a8fcfc7444742d1"],
	["84ab8d11e8951a6551d1e1bf87796a8589da6d47", "e6f0af5d13494109f3e62fc040a5a183307805ca"],
	["1c460e98f870676b15871fe4e5bfeb1a32a3d6d8", "cf584fc058eb8a91e302a591cffdd184aafb82ba"],
	["19c90048d65a5660384d2fb865926a366696d6be", "8ca22647893b763a2edcc9c3a3f7dc8885659190"],
	["c5e28ebcfe00a510922779b2c568cfa52a317445", "7e21266df6e4c3a06ba29136768a8f534b3ef920"],
	["3875679755014997776e091ff8903acfb311dd2f", "98a53c91bb605b1de96372d0e89681192c4cceb4"]
]

[hyprRiver]
description = "River tiling for Hyprland"
authors = ["Zakk"]
output = "riverLayoutPlugin.so"
build = [
	"make all"
]
